### ISSUE TITLE
Wrong exercise number

### ISSUE THREAD

**Issue by ic-it** [fiit-ba/pks-course#1]
https://github.com/fiit-ba/pks-course/blob/7cfe477704d9aca5d0eb2e60045b6236de31f8db/202324/assignments/1_network_communication_analyzer/en.md

```git
- j) The solution to this task is to be presented in the 4th exercise.
+ j) The solution to this task is to be presented in the 3th exercise.
```

**Comment by lukacoff** [comment]
https://github.com/fiit-ba/pks-course/blob/1454d05624c051154c08df027c0aaf9b4d3c2e7a/202324/assignments/1_network_communication_analyzer/en.md

**Comment by lukacoff** [comment]
fixed
